package com.wissen.ems.exception;

public class BusinessRuleViolationException extends RuntimeException {
	// Generated by the IDE
	private static final long serialVersionUID = -738133055472218160L;

	public BusinessRuleViolationException(String message) {
		super(message);
	}
}
