spring:
  application:
    name: employee-management-system

  profiles:
    # We can change this to prod when we want to switch to a persistent data store like MySQL.
    # The switch to prod can also happen via an environment variable if we don't want to edit this file.
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
