spring:
  application:
    name: employee-management-system

  profiles:
    # We can change this to prod when we want to switch to a persistent data store like MySQL.
    # The switch to prod can also happen via an environment variable if we don't want to edit this file.
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Ideally, the front-end URL should not be hard coded.
# We could add it as an environment variable and reference it here.
frontend-url: http://localhost:3000